language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
before_install:
  - npm install -g grunt-cli
  - npm install
scripts:
  ## Test the package
  - npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
notifications:
  email:
    - $GITHUB_EMAIL
